SET XACT_ABORT ON;
IF DB_NAME()<>N'LUMAR_ERP_TEST' THROW 52200,N'ES-4 is restricted to LUMAR_ERP_TEST.',1;
BEGIN TRY BEGIN TRANSACTION;
IF OBJECT_ID(N'dbo.EmployeePayments',N'U') IS NOT NULL THROW 52201,N'ES-4 already exists.',1;
CREATE TABLE dbo.EmployeePayments(
 EmployeePaymentId bigint IDENTITY(1,1) NOT NULL PRIMARY KEY,EmployeeId int NOT NULL,PaymentAmount decimal(18,2) NOT NULL,PaymentType nvarchar(30) NOT NULL,PaymentDate date NOT NULL,AsOfDate date NOT NULL,CashAccountId int NOT NULL,PaymentMethod nvarchar(30) NOT NULL,CurrencyCode char(3) NOT NULL,ReferenceNumber nvarchar(200) NOT NULL,SourceOperationId uniqueidentifier NOT NULL,BalanceBefore decimal(18,2) NOT NULL,BalanceAfter decimal(18,2) NOT NULL,AccountingEventId bigint NULL,Status nvarchar(20) NOT NULL,OriginalPaymentId bigint NULL,ReversalReason nvarchar(500) NULL,ReversedBy nvarchar(100) NULL,ReversedAt datetime2(7) NULL,CreatedBy nvarchar(100) NOT NULL,CreatedAt datetime2(7) NOT NULL CONSTRAINT DF_EmployeePayments_CreatedAt DEFAULT SYSUTCDATETIME(),
 CONSTRAINT FK_EmployeePayments_Employee FOREIGN KEY(EmployeeId) REFERENCES dbo.Employees(EmployeeID),CONSTRAINT FK_EmployeePayments_Cash FOREIGN KEY(CashAccountId) REFERENCES dbo.CashAccounts(CashAccountId),CONSTRAINT FK_EmployeePayments_Event FOREIGN KEY(AccountingEventId) REFERENCES dbo.AccountingEvents(AccountingEventId),CONSTRAINT FK_EmployeePayments_Original FOREIGN KEY(OriginalPaymentId) REFERENCES dbo.EmployeePayments(EmployeePaymentId),CONSTRAINT UQ_EmployeePayments_Operation UNIQUE(SourceOperationId),CONSTRAINT UQ_EmployeePayments_OriginalReversal UNIQUE(OriginalPaymentId),CONSTRAINT CK_EmployeePayments_Amount CHECK(PaymentAmount>0),CONSTRAINT CK_EmployeePayments_Status CHECK(Status IN(N'Posted',N'Reversed')),CONSTRAINT CK_EmployeePayments_Type CHECK(PaymentType IN(N'Individual',N'Reversal')),
 CONSTRAINT CK_EmployeePayments_Reversal CHECK((PaymentType=N'Individual' AND OriginalPaymentId IS NULL AND ReversalReason IS NULL AND ReversedBy IS NULL AND ReversedAt IS NULL) OR (PaymentType=N'Reversal' AND OriginalPaymentId IS NOT NULL AND ReversalReason IS NOT NULL AND ReversedBy IS NOT NULL AND ReversedAt IS NOT NULL)));
CREATE INDEX IX_EmployeePayments_Employee_AsOfDate ON dbo.EmployeePayments(EmployeeId,AsOfDate,EmployeePaymentId);
COMMIT TRANSACTION; END TRY BEGIN CATCH IF XACT_STATE()<>0 ROLLBACK; THROW; END CATCH;