using LUMAR_ERP_API_V2.Data;
using LUMAR_ERP_API_V2.DTOs.Employees;
using Microsoft.Data.SqlClient;

namespace LUMAR_ERP_API_V2.Repositories;

public sealed class EmployeeRepository(ReadOnlySqlConnectionFactory connections) : IEmployeeRepository
{
    public Task<IReadOnlyList<EmployeeListDto>> GetAllAsync(CancellationToken ct) => QueryAsync("SELECT EmployeeID, EmployeeCode, EmployeeName, JobTitle, PhoneNumber, IsActive, Status, DepartmentId FROM dbo.Employees ORDER BY EmployeeName, EmployeeID", null, reader => new EmployeeListDto(reader.GetInt32(0), reader.GetString(1), reader.GetString(2), reader.NullableString("JobTitle"), reader.NullableString("PhoneNumber"), reader.NullableBoolean("IsActive"), reader.GetString(6), reader.GetInt32(7)), ct);
    public async Task<EmployeeDetailsDto?> GetByIdAsync(int employeeId, CancellationToken ct) => (await QueryAsync("SELECT EmployeeID, EmployeeCode, EmployeeName, JobTitle, ScannerCode, PhoneNumber, BaseSalary, Notes, IsActive, SalaryType, FixedSalary, FullName, NationalId, Phone, Email, Address, HireDate, TerminationDate, Status, DepartmentId, BasicSalary, PieceWageRate, OvertimeHourlyRate, CreatedAt, UpdatedAt FROM dbo.Employees WHERE EmployeeID = @id", employeeId, reader => new EmployeeDetailsDto(reader.GetInt32(0), reader.GetString(1), reader.GetString(2), reader.NullableString("JobTitle"), reader.NullableString("ScannerCode"), reader.NullableString("PhoneNumber"), reader.NullableDecimal("BaseSalary"), reader.NullableString("Notes"), reader.NullableBoolean("IsActive"), reader.NullableString("SalaryType"), reader.NullableDecimal("FixedSalary"), reader.GetString(11), reader.NullableString("NationalId"), reader.NullableString("Phone"), reader.NullableString("Email"), reader.NullableString("Address"), reader.GetDateTime(16), reader.NullableDateTime("TerminationDate"), reader.GetString(18), reader.GetInt32(19), reader.GetDecimal(20), reader.GetDecimal(21), reader.GetDecimal(22), reader.GetDateTime(23), reader.NullableDateTime("UpdatedAt")), ct)).FirstOrDefault();
    public Task<IReadOnlyList<DepartmentDto>> GetDepartmentsAsync(CancellationToken ct) => QueryAsync("SELECT DepartmentId, DepartmentCode, DepartmentName, Description, IsActive, CreatedAt, UpdatedAt FROM dbo.Departments ORDER BY DepartmentName, DepartmentId", null, reader => new DepartmentDto(reader.GetInt32(0), reader.GetString(1), reader.GetString(2), reader.NullableString("Description"), reader.GetBoolean(4), reader.GetDateTime(5), reader.NullableDateTime("UpdatedAt")), ct);
    public Task<IReadOnlyList<EmployeeAttendanceDto>> GetAttendanceAsync(int employeeId, CancellationToken ct) => QueryAsync("SELECT EmployeeAttendanceId, EmployeeId, AttendanceDate, CheckInTime, CheckOutTime, WorkedHours, OvertimeHours, IsAbsent, AbsenceReason, Notes, CreatedAt FROM dbo.EmployeeAttendances WHERE EmployeeId = @id ORDER BY AttendanceDate DESC, EmployeeAttendanceId DESC", employeeId, reader => new EmployeeAttendanceDto(reader.GetInt32(0), reader.GetInt32(1), reader.GetDateTime(2), reader.NullableDateTime("CheckInTime"), reader.NullableDateTime("CheckOutTime"), reader.GetDecimal(5), reader.GetDecimal(6), reader.GetBoolean(7), reader.NullableString("AbsenceReason"), reader.NullableString("Notes"), reader.GetDateTime(10)), ct);
    public Task<IReadOnlyList<LeaveRequestDto>> GetLeaveRequestsAsync(int employeeId, CancellationToken ct) => QueryAsync("SELECT LeaveRequestId, EmployeeId, LeaveType, StartDate, EndDate, RequestedDays, Status, Reason, ApprovedBy, ApprovedAt, CreatedAt FROM dbo.LeaveRequests WHERE EmployeeId = @id ORDER BY CreatedAt DESC, LeaveRequestId DESC", employeeId, reader => new LeaveRequestDto(reader.GetInt32(0), reader.GetInt32(1), reader.GetString(2), reader.GetDateTime(3), reader.GetDateTime(4), reader.GetDecimal(5), reader.GetString(6), reader.NullableString("Reason"), reader.NullableString("ApprovedBy"), reader.NullableDateTime("ApprovedAt"), reader.GetDateTime(10)), ct);
    public Task<IReadOnlyList<EmployeeDrawDto>> GetDrawsAsync(string employeeCode, CancellationToken ct) => QueryAsync("SELECT DrawID, EmployeeCode, DrawDate, Amount, Notes FROM dbo.Employee_Draws WHERE EmployeeCode = @code ORDER BY DrawDate DESC, DrawID DESC", employeeCode, reader => new EmployeeDrawDto(reader.GetInt32(0), reader.NullableString("EmployeeCode"), reader.NullableDateTime("DrawDate"), reader.NullableDecimal("Amount"), reader.NullableString("Notes")), ct);
    public Task<IReadOnlyList<EmployeeDocumentDto>> GetDocumentsAsync(int employeeId, CancellationToken ct) => QueryAsync("SELECT EmployeeDocumentId, EmployeeId, DocumentType, DocumentNumber, IssueDate, ExpiryDate, FilePath, Notes, CreatedAt FROM dbo.EmployeeDocuments WHERE EmployeeId = @id ORDER BY CreatedAt DESC, EmployeeDocumentId DESC", employeeId, reader => new EmployeeDocumentDto(reader.GetInt32(0), reader.GetInt32(1), reader.GetString(2), reader.NullableString("DocumentNumber"), reader.NullableDateTime("IssueDate"), reader.NullableDateTime("ExpiryDate"), reader.NullableString("FilePath"), reader.NullableString("Notes"), reader.GetDateTime(8)), ct);
    public Task<IReadOnlyList<EmployeeWorkflowDto>> GetWorkflowAsync(string employeeCode, CancellationToken ct) => QueryAsync("SELECT EmployeeCode, WorkStage FROM dbo.Employee_Workflow WHERE EmployeeCode = @code", employeeCode, reader => new EmployeeWorkflowDto(reader.GetString(0), reader.NullableString("WorkStage")), ct);

    private async Task<IReadOnlyList<T>> QueryAsync<T>(string sql, object? parameter, Func<SqlDataReader, T> map, CancellationToken ct)
    { await using var connection = connections.Create(); await connection.OpenAsync(ct); await using var command = new SqlCommand(sql, connection); if (parameter is not null) command.Parameters.AddWithValue(sql.Contains("@code") ? "@code" : "@id", parameter); await using var reader = await command.ExecuteReaderAsync(ct); var items = new List<T>(); while (await reader.ReadAsync(ct)) items.Add(map(reader)); return items; }
}