using LUMAR_ERP_API_V2.Data;
using LUMAR_ERP_API_V2.DTOs.Payroll;
using Microsoft.Data.SqlClient;
namespace LUMAR_ERP_API_V2.Repositories;
public sealed class PayrollRepository(ReadOnlySqlConnectionFactory connections) : IPayrollRepository
{
    public Task<IReadOnlyList<PayrollPeriodDto>> GetPeriodsAsync(CancellationToken ct) => QueryAsync("SELECT PayrollPeriodId, PeriodCode, StartDate, EndDate, Status, Notes, GeneratedAt, ApprovedAt, CreatedAt FROM dbo.PayrollPeriods ORDER BY StartDate DESC, PayrollPeriodId DESC", null, MapPeriod, ct);
    public async Task<PayrollPeriodDto?> GetPeriodAsync(int id, CancellationToken ct) => (await QueryAsync("SELECT PayrollPeriodId, PeriodCode, StartDate, EndDate, Status, Notes, GeneratedAt, ApprovedAt, CreatedAt FROM dbo.PayrollPeriods WHERE PayrollPeriodId = @id", id, MapPeriod, ct)).FirstOrDefault();
    public Task<IReadOnlyList<PayrollRecordDto>> GetRecordsAsync(CancellationToken ct) => QueryAsync("SELECT PayrollRecordId, PayrollPeriodId, EmployeeId, BasicSalaryAmount, PieceWageAmount, AttendanceAdjustmentAmount, OvertimeAmount, GrossAmount, DeductionsAmount, NetAmount, Status, Notes, CreatedAt FROM dbo.PayrollRecords ORDER BY CreatedAt DESC, PayrollRecordId DESC", null, MapRecord, ct);
    public async Task<PayrollRecordDto?> GetRecordAsync(int id, CancellationToken ct) => (await QueryAsync("SELECT PayrollRecordId, PayrollPeriodId, EmployeeId, BasicSalaryAmount, PieceWageAmount, AttendanceAdjustmentAmount, OvertimeAmount, GrossAmount, DeductionsAmount, NetAmount, Status, Notes, CreatedAt FROM dbo.PayrollRecords WHERE PayrollRecordId = @id", id, MapRecord, ct)).FirstOrDefault();
    public Task<IReadOnlyList<PayrollItemDto>> GetItemsAsync(int recordId, CancellationToken ct) => QueryAsync("SELECT PayrollItemId, PayrollRecordId, ItemType, ItemName, Quantity, Rate, Amount, Notes FROM dbo.PayrollItems WHERE PayrollRecordId = @id ORDER BY PayrollItemId", recordId, reader => new PayrollItemDto(reader.GetInt32(0), reader.GetInt32(1), reader.GetString(2), reader.GetString(3), reader.GetDecimal(4), reader.GetDecimal(5), reader.GetDecimal(6), reader.NullableString("Notes")), ct);
    public Task<IReadOnlyList<EmployeePayrollSummaryDto>> GetEmployeeSummariesAsync(int periodId, CancellationToken ct) => QueryAsync("SELECT EmployeeId, PayrollPeriodId, BasicSalaryAmount, PieceWageAmount, AttendanceAdjustmentAmount, OvertimeAmount, GrossAmount, DeductionsAmount, NetAmount FROM dbo.PayrollRecords WHERE PayrollPeriodId = @id ORDER BY EmployeeId", periodId, reader => new EmployeePayrollSummaryDto(reader.GetInt32(0), reader.GetInt32(1), reader.GetDecimal(2), reader.GetDecimal(3), reader.GetDecimal(4), reader.GetDecimal(5), reader.GetDecimal(6), reader.GetDecimal(7), reader.GetDecimal(8)), ct);
    public Task<IReadOnlyList<PieceWageRecordDto>> GetPieceWagesAsync(CancellationToken ct) => QueryAsync("SELECT PieceWageRecordID, OrderID, OrderItemID, PieceID, TrackingEventID, EmployeeId, EmployeeCode, PieceType, Stage, Quantity, WageRate, TotalWage, PayrollPeriodId, PayrollRecordId, Status, Notes, CreatedAt FROM dbo.PieceWageRecords ORDER BY CreatedAt DESC, PieceWageRecordID DESC", null, reader => new PieceWageRecordDto(reader.GetInt32(0), reader.GetInt32(1), reader.GetInt32(2), reader.GetInt32(3), reader.GetInt32(4), reader.NullableInt32("EmployeeId"), reader.NullableString("EmployeeCode"), reader.GetString(7), reader.GetString(8), reader.GetDecimal(9), reader.GetDecimal(10), reader.GetDecimal(11), reader.NullableInt32("PayrollPeriodId"), reader.NullableInt32("PayrollRecordId"), reader.GetString(14), reader.NullableString("Notes"), reader.GetDateTime(16)), ct);
    public Task<IReadOnlyList<PieceWageRateDto>> GetPieceWageRatesAsync(CancellationToken ct) => QueryAsync("SELECT PieceWageRateID, PieceType, Stage, WageRate, IsActive, Notes, CreatedAt, UpdatedAt FROM dbo.PieceWageRates ORDER BY PieceType, Stage, PieceWageRateID", null, reader => new PieceWageRateDto(reader.GetInt32(0), reader.GetString(1), reader.GetString(2), reader.GetDecimal(3), reader.GetBoolean(4), reader.NullableString("Notes"), reader.GetDateTime(6), reader.NullableDateTime("UpdatedAt")), ct);
    private static PayrollPeriodDto MapPeriod(SqlDataReader reader) => new(reader.GetInt32(0), reader.GetString(1), reader.GetDateTime(2), reader.GetDateTime(3), reader.GetString(4), reader.NullableString("Notes"), reader.NullableDateTime("GeneratedAt"), reader.NullableDateTime("ApprovedAt"), reader.GetDateTime(8));
    private static PayrollRecordDto MapRecord(SqlDataReader reader) => new(reader.GetInt32(0), reader.GetInt32(1), reader.GetInt32(2), reader.GetDecimal(3), reader.GetDecimal(4), reader.GetDecimal(5), reader.GetDecimal(6), reader.GetDecimal(7), reader.GetDecimal(8), reader.GetDecimal(9), reader.GetString(10), reader.NullableString("Notes"), reader.GetDateTime(12));
    private async Task<IReadOnlyList<T>> QueryAsync<T>(string sql, int? id, Func<SqlDataReader, T> map, CancellationToken ct) { await using var connection = connections.Create(); await connection.OpenAsync(ct); await using var command = new SqlCommand(sql, connection); if (id.HasValue) command.Parameters.AddWithValue("@id", id.Value); await using var reader = await command.ExecuteReaderAsync(ct); var items = new List<T>(); while (await reader.ReadAsync(ct)) items.Add(map(reader)); return items; }
}