using LUMAR_ERP_API_V2.Data; using LUMAR_ERP_API_V2.DTOs.Suppliers; using Microsoft.Data.SqlClient;
namespace LUMAR_ERP_API_V2.Repositories;
public sealed class SupplierRepository(ReadOnlySqlConnectionFactory connections) : ISupplierRepository
{
    public Task<IReadOnlyList<SupplierListDto>> GetAllAsync(CancellationToken ct) => QueryAsync("SELECT SupplierId, SupplierCode, SupplierName, Phone, Email, IsActive FROM dbo.Suppliers ORDER BY SupplierName, SupplierId", null, r => new SupplierListDto(r.GetInt32(0),r.GetString(1),r.GetString(2),r.NullableString("Phone"),r.NullableString("Email"),r.GetBoolean(5)),ct);
    public async Task<SupplierDetailsDto?> GetByIdAsync(int id,CancellationToken ct) => (await QueryAsync("SELECT SupplierId, SupplierCode, SupplierName, Phone, Email, Address, IsActive, CreatedAt, UpdatedAt FROM dbo.Suppliers WHERE SupplierId=@id",id,r=>new SupplierDetailsDto(r.GetInt32(0),r.GetString(1),r.GetString(2),r.NullableString("Phone"),r.NullableString("Email"),r.NullableString("Address"),r.GetBoolean(6),r.GetDateTime(7),r.NullableDateTime("UpdatedAt")),ct)).FirstOrDefault();
    public Task<IReadOnlyList<SupplierTransactionDto>> GetTransactionsAsync(int id,CancellationToken ct) => QueryAsync("SELECT SupplierTransactionId,SupplierId,ReferenceNumber,TransactionType,Amount,Description,CreatedAt FROM dbo.SupplierTransactions WHERE SupplierId=@id ORDER BY CreatedAt DESC,SupplierTransactionId DESC",id,r=>new SupplierTransactionDto(r.GetInt32(0),r.GetInt32(1),r.GetString(2),r.GetString(3),r.GetDecimal(4),r.NullableString("Description"),r.GetDateTime(6)),ct);
    public Task<IReadOnlyList<SupplierLedgerEntryDto>> GetLedgerAsync(int id,CancellationToken ct) => QueryAsync("SELECT SupplierLedgerEntryId,SupplierId,ReferenceNumber,DebitAmount,CreditAmount,BalanceAfterTransaction,CreatedAt FROM dbo.SupplierLedgerEntries WHERE SupplierId=@id ORDER BY CreatedAt DESC,SupplierLedgerEntryId DESC",id,r=>new SupplierLedgerEntryDto(r.GetInt32(0),r.GetInt32(1),r.GetString(2),r.GetDecimal(3),r.GetDecimal(4),r.GetDecimal(5),r.GetDateTime(6)),ct);
    public Task<IReadOnlyList<SupplierInvoiceDto>> GetInvoicesAsync(int id,CancellationToken ct) => QueryAsync("SELECT SupplierInvoiceId,SupplierId,PurchaseOrderId,InvoiceNumber,InvoiceDate,DueDate,TotalAmount,AmountPaid,Status,Notes,CreatedAt FROM dbo.SupplierInvoices WHERE SupplierId=@id ORDER BY InvoiceDate DESC,SupplierInvoiceId DESC",id,MapInvoice,ct);
    public Task<IReadOnlyList<SupplierPaymentDto>> GetPaymentsAsync(int id,CancellationToken ct) => QueryAsync("SELECT SupplierPaymentId,SupplierId,PaymentNumber,PaymentDate,Amount,PaymentMethod,ReferenceNumber,Notes,CreatedAt,JournalEntryId FROM dbo.SupplierPayments WHERE SupplierId=@id ORDER BY PaymentDate DESC,SupplierPaymentId DESC",id,MapPayment,ct);
    public Task<IReadOnlyList<SupplierPaymentAllocationDto>> GetAllocationsAsync(int id,CancellationToken ct) => QueryAsync("SELECT a.SupplierPaymentAllocationId,a.SupplierPaymentId,a.SupplierInvoiceId,a.AllocatedAmount,a.AllocationDate,a.Notes,a.CreatedAt FROM dbo.SupplierPaymentAllocations a JOIN dbo.SupplierPayments p ON p.SupplierPaymentId=a.SupplierPaymentId WHERE p.SupplierId=@id ORDER BY a.AllocationDate DESC,a.SupplierPaymentAllocationId DESC",id,MapAllocation,ct);
    private static SupplierInvoiceDto MapInvoice(SqlDataReader r)=>new(r.GetInt32(0),r.GetInt32(1),r.GetInt32(2),r.GetString(3),r.GetDateTime(4),r.GetDateTime(5),r.GetDecimal(6),r.GetDecimal(7),r.GetString(8),r.NullableString("Notes"),r.GetDateTime(10)); private static SupplierPaymentDto MapPayment(SqlDataReader r)=>new(r.GetInt32(0),r.GetInt32(1),r.GetString(2),r.GetDateTime(3),r.GetDecimal(4),r.NullableString("PaymentMethod"),r.NullableString("ReferenceNumber"),r.NullableString("Notes"),r.GetDateTime(8),r.NullableInt32("JournalEntryId")); private static SupplierPaymentAllocationDto MapAllocation(SqlDataReader r)=>new(r.GetInt32(0),r.GetInt32(1),r.GetInt32(2),r.GetDecimal(3),r.GetDateTime(4),r.NullableString("Notes"),r.GetDateTime(6));
    private async Task<IReadOnlyList<T>> QueryAsync<T>(string sql,int? id,Func<SqlDataReader,T> map,CancellationToken ct){await using var c=connections.Create();await c.OpenAsync(ct);await using var cmd=new SqlCommand(sql,c);if(id.HasValue)cmd.Parameters.AddWithValue("@id",id.Value);await using var r=await cmd.ExecuteReaderAsync(ct);var items=new List<T>();while(await r.ReadAsync(ct))items.Add(map(r));return items;}
}