namespace LUMAR_ERP_API_V2.DTOs.Loyalty;

public sealed record VipLevelEvaluationCriteriaDto(
    int VipLevelId,
    string Code,
    string DisplayName,
    int Priority,
    int MinimumDirectReferrals,
    int MinimumOwnOrders,
    int MinimumNetworkOrders,
    int MinimumNetworkSize,
    decimal MinimumScore,
    decimal DirectReferralWeight,
    decimal OwnOrderWeight,
    decimal NetworkOrderWeight,
    decimal NetworkSizeWeight,
    bool IsActive);

public sealed record VipLevelEvaluationSourceDto(
    int CustomerId,
    string? CustomerCode,
    string? CustomerName,
    int? CurrentVipLevelId,
    string? CurrentVipLevelCode,
    string? CurrentVipLevelDisplayName,
    DateTime? LastEvaluatedAtUtc,
    string? PreviousReason,
    int DirectReferralCount,
    int Level1ReferralCount,
    int Level2ReferralCount,
    int Level3ReferralCount,
    int Level4ReferralCount,
    int NetworkSize,
    int NetworkMaxDepth,
    int OwnOrderCount,
    int NetworkOrderCount);

public sealed record VipLevelEvaluationDto(
    int CustomerId,
    string? CustomerCode,
    string? CustomerName,
    int? PreviousVipLevelId,
    string? PreviousVipLevelCode,
    string? PreviousVipLevelDisplayName,
    int EvaluatedVipLevelId,
    string EvaluatedVipLevelCode,
    string EvaluatedVipLevelDisplayName,
    int DirectReferralCount,
    int Level1ReferralCount,
    int Level2ReferralCount,
    int Level3ReferralCount,
    int Level4ReferralCount,
    int NetworkSize,
    int NetworkMaxDepth,
    int OwnOrderCount,
    int NetworkOrderCount,
    decimal Score,
    string Reason,
    DateTime EvaluatedAtUtc,
    bool Changed);

public sealed record VipCustomerListItemDto(
    int CustomerId,
    string? CustomerCode,
    string? CustomerName,
    int VipLevelId,
    string VipLevelCode,
    string VipLevelDisplayName,
    int VipLevelPriority,
    decimal Score,
    int DirectReferralCount,
    int OwnOrderCount,
    int NetworkOrderCount,
    int NetworkSize,
    int NetworkMaxDepth,
    DateTime EvaluatedAtUtc);
