namespace LUMAR_ERP_API_V2.DTOs.Production;

public sealed record PieceDto(int PieceId, int OrderItemId, string TrackingCode, string PieceStatus, int PieceNumber, DateTime CreatedDate, string PieceType);
public sealed record WorkCardDto(int PieceId, int OrderItemId, int OrderId, string OrderNumber, int PieceNumber, string TrackingCode, string? CustomerCode, string? CustomerName, string? PhoneNumber, string PieceType, int Quantity, string? FabricType, string? FabricColor, string? Notes1, string? Notes2, string? MeasurementSnapshot, DateTime? DeliveryDate, string PieceStatus, IReadOnlyList<TrackingEventDto> TrackingHistory);
public sealed record ProductionDashboardDto(int TotalPieces, int InProductionPieces, int ReadyPieces, int DeliveredPieces, int ActiveStages, int ReadyForSaleProducts, int DelayedPieces);
public sealed record ReadyMadeProductionOrderDto(int ReadyMadeProductionOrderId, string ProductionOrderNumber, string ProductionName, decimal TotalCost, decimal ProfitPercentage, decimal SuggestedSellingPrice, string Status, string? Notes, DateTime CreatedAt);
public sealed record ReadyMadeProductionOrderItemDto(int ReadyMadeProductionOrderItemId, int ReadyMadeProductionOrderId, string PieceType, int Quantity, string? FabricCode, string? FabricType, string? FabricColor, string? CatalogNumber, decimal? FabricCost, decimal? PieceCost, decimal? LineTotal, string? MeasurementSnapshot, string PieceStatus, DateTime CreatedAt);
public sealed record ReadyMadeProductionPieceDto(int ReadyMadeProductionOrderPieceInstanceId, int ReadyMadeProductionOrderItemId, int PieceNumber, string TrackingCode, string PieceStatus, DateTime CreatedAt);
public sealed record ProductionDeliveryDto(int OrderId, string OrderNumber, int CustomerId, string? CustomerCode, string? CustomerName, string? PhoneNumber, string OrderStatus, DateTime? DeliveryDate);
public sealed record PieceTrackingDto(int TrackingCode, int? InvoiceId, int? CustomerId, string? ItemType, string? Status, string? CuttingEmployee, string? SewingEmployee, string? IroningEmployee, DateTime? CreatedDate, DateTime? CuttingDate, DateTime? SewingDate, DateTime? IroningDate, bool? IsCompleted, bool? IsDelivered, DateTime? DeliveryDate, bool? IsOnHold, string? HoldReason);
public sealed record ProductionStageDto(string Stage, string Status);
public sealed record ScannerDto(int ScannerId, string ScannerCode, string ScannerName, string? Description, bool IsActive, DateTime CreatedAt, DateTime? UpdatedAt);
public sealed record LiveScanDto(int Id, int? TrackingCode, DateTime? ScanTime);
public sealed record TrackingEventDto(int TrackingEventId, int? OrderItemId, int? OrderId, string? TrackingCode, string Stage, string Status, DateTime EventTime, string? EmployeeCode, string? Notes, bool IsReverted, DateTime? RevertedAt, int? PieceId, int? ReadyMadeProductionOrderPieceInstanceId);
public sealed record PieceWageDto(int PieceWageRecordId, int OrderId, int OrderItemId, int PieceId, int TrackingEventId, int? EmployeeId, string? EmployeeCode, string PieceType, string Stage, decimal Quantity, decimal WageRate, decimal TotalWage, int? PayrollPeriodId, int? PayrollRecordId, string Status, string? Notes, DateTime CreatedAt);
public sealed record PieceWageRateDto(int PieceWageRateId, string PieceType, string Stage, decimal WageRate, bool IsActive, string? Notes, DateTime CreatedAt, DateTime? UpdatedAt);